package main

//"os"
//"xyz"
//"github.com/colinarticulate/scanScheduler"

var params72 = []string{
	"pocketsphinx_continuous",
	"-alpha", "0.97",
	"-backtrace", "yes",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cmn", "live",
	"-cmninit", "61.61,8.03,-6.54,4.13,-3.74,9.61,-5.77,-16.52,-13.85,-3.98,2.30,2.59,-1.94",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db.phone",
	"-dither", "yes", //yes
	"-doublebw", "yes", //yes
	"-featparams", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us/feat.params",
	"-frate", "72",
	"-fsgusefiller", "no",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-infile", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/allowed1_philip_fixed_trimmed.wav",
	"-jsgf", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/forced_align_2668db47-d3ce-4760-ab4b-60b9b8a6c46e_allowed1_philip_fixed_trimmed.wav.jsgf",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/log/d0c65f23-d9cc-4047-8f3c-3a91db3623ff_2668db47_frate_72_from_go_XYZ-PLUS.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-nwpen", "1",
	"-pbeam", "1e-10000",
	"-pip", "1.15", //1.15
	"-pl_window", "0",
	"-remove_dc", "no",
	"-remove_noise", "yes",
	"-remove_silence", "yes", //yes
	"-topn", "6",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "1.5",
	"-wbeam", "1e-10000",
	"-wip", "0.25",
	"-wlen", "0.032",
}

var params125 = []string{
	"pocketsphinx_continuous",
	"-alpha", "0.97",
	"-backtrace", "yes",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cmn", "live",
	"-cmninit", "48.66,4.31,-7.12,5.61,-1.63,9.01,-4.65,-17.99,-16.52,-5.18,3.45,2.53,-1.34",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db.phone",
	"-dither", "no",
	"-doublebw", "no",
	"-featparams", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us/feat.params",
	"-frate", "125",
	"-fsgusefiller", "no",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-infile", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/allowed1_philip_fixed_trimmed.wav",
	"-jsgf", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/forced_align_a3ecf04d-a77a-4269-9eb5-395f8dfbdd8a_allowed1_philip_fixed_trimmed.wav.jsgf",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/log/e1e0d844-812b-496c-83fb-712de847f8a7_a3ecf04d_frate_125_from_go_.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "256",
	"-nwpen", "1",
	"-pbeam", "1e-10000",
	"-pip", "1",
	"-pl_window", "0",
	"-remove_dc", "no",
	"-remove_noise", "yes",
	"-remove_silence", "no",
	"-topn", "4",
	"-vad_postspeech", "25",
	"-vad_prespeech", "5",
	"-vad_startspeech", "8",
	"-vad_threshold", "1",
	"-wbeam", "1e-10000",
	"-wip", "0.5",
	"-wlen", "0.016",
}

var params105 = []string{
	"pocketsphinx_continuous",
	"-alpha", "0.97",
	"-backtrace", "yes",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cmn", "live",
	"-cmninit", "53.92,4.73,-7.01,5.40,-1.92,8.97,-4.24,-17.95,-17.00,-6.15,2.58,1.61,-1.69",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db.phone",
	"-dither", "no",
	"-doublebw", "no",
	"-featparams", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us/feat.params",
	"-frate", "105",
	"-fsgusefiller", "no",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-infile", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/allowed1_philip_fixed_trimmed.wav",
	"-jsgf", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/forced_align_9ddb7131-fa08-4bc4-b44c-814b2ed9917e_allowed1_philip_fixed_trimmed.wav.jsgf",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/log/c061830a-8106-4e06-ae16-18feb072ea45_9ddb7131_frate_105_from_go_.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-nwpen", "1",
	"-pbeam", "1e-10000",
	"-pip", "1",
	"-pl_window", "0",
	"-remove_dc", "no",
	"-remove_noise", "yes",
	"-remove_silence", "no",
	"-topn", "4",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "1.5",
	"-wbeam", "1e-10000",
	"-wip", "0.5",
	"-wlen", "0.020",
}

var params80 = []string{
	"pocketsphinx_continuous",
	"-alpha", "0.97",
	"-backtrace", "yes",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cmn", "live",
	"-cmninit", "60.83,7.43,-6.07,4.54,-3.88,9.48,-5.85,-16.81,-13.89,-3.82,2.39,2.53,-1.88",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db.phone",
	"-dither", "yes",
	"-doublebw", "yes",
	"-featparams", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us/feat.params",
	"-frate", "80",
	"-fsgusefiller", "no",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-infile", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/allowed1_philip_fixed_trimmed.wav",
	"-jsgf", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/forced_align_4311b957-22a7-446c-85d9-d154d4156d02_allowed1_philip_fixed_trimmed.wav.jsgf",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/log/4f0e00fa-9d20-4096-8bb5-8aeedc110e52_4311b957_frate_80_from_go_.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-nwpen", "1",
	"-pbeam", "1e-10000",
	"-pip", "1.15",
	"-pl_window", "0",
	"-remove_dc", "no",
	"-remove_noise", "yes",
	"-remove_silence", "yes", //yes
	"-topn", "6",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "1.5",
	"-wbeam", "1e-10000",
	"-wip", "0.25",
	"-wlen", "0.028",
}

var params91 = []string{
	"pocketsphinx_continuous",
	"-alpha", "0.97",
	"-backtrace", "yes",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cmn", "live",
	"-cmninit", "55.22,5.33,-6.78,5.07,-2.13,9.10,-4.03,-17.60,-16.77,-6.25,2.43,1.62,-1.56",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db.phone",
	"-dither", "no",
	"-doublebw", "no",
	"-featparams", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us/feat.params",
	"-frate", "91",
	"-fsgusefiller", "no",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-infile", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/allowed1_philip_fixed_trimmed.wav",
	"-jsgf", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/forced_align_1eed3902-f7e5-444b-a4b8-29b5c47ea52e_allowed1_philip_fixed_trimmed.wav.jsgf",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip/Temp_990ba583-5249-41f3-8d42-0617f9eea6cd/log/f7a95619-d7c5-42a9-b548-561187b350da_1eed3902_frate_91_from_go_.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-nwpen", "1",
	"-pbeam", "1e-10000",
	"-pip", "1",
	"-pl_window", "0",
	"-remove_dc", "no",
	"-remove_noise", "yes",
	"-remove_silence", "no",
	"-topn", "4",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "0.5",
	"-wbeam", "1e-10000",
	"-wip", "0.5",
	"-wlen", "0.024",
}

//--------------------------- BATCH -------------------------

var batch_params72 = []string{
	"pocketsphinx_batch",
	"-adcin", "yes",
	"-alpha", "0.97",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cepdir", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/audio",
	"-cepext", ".wav",
	"-ctl", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/ctl/ctl_allowed1_philip_fixed_trimmed.txt",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db_v2_inference.phone",
	"-dither", "yes",
	"-doublebw", "yes",
	//"-featparams", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/feat_batch.param",
	"-frate", "72",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-lm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us.lm.bin",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/log/7eb4a3dd-1fb5-4e64-b7f9-fb3cbbca5829_-frate_72_BATCH_xyz_plus.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-pbeam", "1e-10000",
	"-pip", "1.15",
	"-pl_window", "0",
	"-remove_noise", "yes",
	"-remove_silence", "yes",
	"-topn", "6",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "1.5",
	"-wbeam", "1e-10000",
	"-wip", "0.25",
	"-wlen", "0.032",
}

var batch_params80 = []string{
	"pocketsphinx_batch",
	"-adcin", "yes",
	"-alpha", "0.97",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cepdir", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/audio",
	"-cepext", ".wav",
	"-ctl", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/ctl/ctl_allowed1_philip_fixed_trimmed.txt",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db_v2_inference.phone",
	"-dither", "yes",
	"-doublebw", "yes",
	"-frate", "80",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-lm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us.lm.bin",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/log/7eb4a3dd-1fb5-4e64-b7f9-fb3cbbca5829_-frate_80_BATCH_xyz_plus.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-pbeam", "1e-10000",
	"-pip", "1.15",
	"-pl_window", "0",
	"-remove_noise", "yes",
	"-remove_silence", "yes",
	"-topn", "6",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "1.5",
	"-wbeam", "1e-10000",
	"-wip", "0.25",
	"-wlen", "0.028",
}

var batch_params91 = []string{
	"pocketsphinx_batch",
	"-adcin", "yes",
	"-alpha", "0.97",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cepdir", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/audio",
	"-cepext", ".wav",
	"-ctl", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/ctl/ctl_allowed1_philip_fixed_trimmed.txt",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db_v2_inference.phone",
	"-dither", "no",
	"-doublebw", "no",
	"-frate", "91",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-lm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us.lm.bin",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/log/7eb4a3dd-1fb5-4e64-b7f9-fb3cbbca5829_-frate_91_BATCH_xyz_plus.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-pbeam", "1e-10000",
	"-pip", "1",
	"-pl_window", "0",
	"-remove_noise", "yes",
	"-remove_silence", "no",
	"-topn", "4",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "0.5",
	"-wbeam", "1e-10000",
	"-wip", "0.5",
	"-wlen", "0.024",
}

var batch_params105 = []string{
	"pocketsphinx_batch",
	"-adcin", "yes",
	"-alpha", "0.97",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cepdir", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/audio",
	"-cepext", ".wav",
	"-ctl", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/ctl/ctl_allowed1_philip_fixed_trimmed.txt",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db_v2_inference.phone",
	"-dither", "no",
	"-doublebw", "no",
	"-frate", "105",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-lm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us.lm.bin",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/log/7eb4a3dd-1fb5-4e64-b7f9-fb3cbbca5829_-frate_105_BATCH_xyz_plus.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "512",
	"-pbeam", "1e-10000",
	"-pip", "1",
	"-pl_window", "0",
	"-remove_noise", "yes",
	"-remove_silence", "no",
	"-topn", "4",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "5",
	"-vad_threshold", "1.5",
	"-wbeam", "1e-10000",
	"-wip", "0.5",
	"-wlen", "0.020",
}

var batch_params125 = []string{
	"pocketsphinx_batch",
	"-adcin", "yes",
	"-alpha", "0.97",
	"-beam", "1e-10000",
	"-bestpath", "no",
	"-cepdir", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/audio",
	"-cepext", ".wav",
	"-ctl", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/ctl/ctl_allowed1_philip_fixed_trimmed.txt",
	"-dict", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/dictionaries/art_db_v2_inference.phone",
	"-dither", "no",
	"-doublebw", "no",
	"-frate", "125",
	"-fwdflat", "no",
	"-hmm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us",
	"-lm", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/model/art-en-us/en-us.lm.bin",
	"-logfn", "/home/dbarbera/Repositories/articulate-pocketsphinx-go/caller_plus/test_data/allowed1_philip_allowed/log/7eb4a3dd-1fb5-4e64-b7f9-fb3cbbca5829_-frate_125_BATCH_xyz_plus.log",
	"-lpbeam", "1e-10000",
	"-lponlybeam", "1e-10000",
	"-lw", "6",
	"-maxhmmpf", "-1",
	"-maxwpf", "-1",
	"-nfft", "256",
	"-pbeam", "1e-10000",
	"-pip", "1",
	"-pl_window", "0",
	"-remove_noise", "yes",
	"-remove_silence", "no",
	"-topn", "4",
	"-vad_postspeech", "20",
	"-vad_prespeech", "5",
	"-vad_startspeech", "8",
	"-vad_threshold", "1",
	"-wbeam", "1e-10000",
	"-wip", "0.5",
	"-wlen", "0.016",
}
